server:
 port: 8080
 servlet:
#url中添加项目名
  context-path: /jobspider

#mybatis:
# mapper-locations: classpath:mappers/*.xml

#mongodb
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jobspiderdb
#  aop:
#   proxy-target-class: false
##  jackson:
##    date-format: yyyy-MM-dd
##    time-zone: GMT+8
##    serialization:
##      write-dates-as-timestamps: false

#关闭mongodb中“Found cycle for field 'xx' in type 'xx' for path 'xx'”日志
logging:
 level:
  org:
   springframework:
    data:
     mongodb:
      core:
       index: false

#shiro
#shiro:
#  hash-algorithm-name: md5
#  hash-iterations: 2
  #任何人均可访问
#  anon-urls:
#  - /**
 #login-url: /page/login.html
 #log-out-url: page/index.html
  #无权限界面
 #unauthorizedUrl: /403
 #successUrl: page/index
#  authc-ulrs:
#  - /deliverRecords*

