server:
 port: 8088
 servlet:
#url中添加项目名
  context-path: /jobspider

#mybatis:
# mapper-locations: classpath:mappers/*.xml

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jobspiderdb
#  aop:
#   proxy-target-class: false

